#!/bin/bash

log_file="/opt/metrics.d/log_exporter.log"
metrics_db="/opt/metrics.d/aleo.metrics"

export PATH="/usr/local/bin:$PATH"

END_POINT="http:/127.0.0.1:3032/"

re='^[0-9]+$'

function get_Data() {

    getnodestats=$(curl -s --data-binary '{"jsonrpc": "2.0", "id":"documentation", "method": "getnodestate" }' -H 'content-type: application/json' "$END_POINT" | jq .result)
    peers_connected=$(curl -s --data-binary '{"jsonrpc": "2.0", "id":"documentation", "method": "getconnectedpeers" }' -H 'content-type: application/json' "$END_POINT" | jq -r .result)
    leaderboard=$(curl -s  curl https://www.aleo.network/api/leaderboard?search=$(grep "\-\-miner aleo" /etc/systemd/system/aleod-miner.service | grep -Eo "aleo.+"))
    
}

function metrics_collector() {
    # nodeinfo
    IFS=' ' read -r -a nodeinfo_arr <<<$(echo $(echo "$getnodestats" | jq '.type,.status,.latest_block_height,.latest_cumulative_weight,.number_of_candidate_peers,.number_of_connected_peers,.number_of_connected_sync_nodes,.version'))

    is_miner="${nodeinfo_arr[0]}"
    is_syncing="${nodeinfo_arr[1]}"

    if [[ $is_miner =~ "Miner" ]]; then
        aleo_nodeinfo_is_miner=0
    else
        aleo_nodeinfo_is_miner=1
    fi

    if [[ $is_syncing =~ "Syncing" ]]; then
        aleo_nodeinfo_is_syncing=0
    else
        aleo_nodeinfo_is_syncing=1
    fi
    
    aleo_nodeinfo_latest_block_height="${nodeinfo_arr[2]}"
    aleo_nodeinfo_latest_cumulative_weight="${nodeinfo_arr[3]}"
    aleo_nodeinfo_number_of_candidate_peers="${nodeinfo_arr[4]}"
    aleo_nodeinfo_number_of_connected_peers="${nodeinfo_arr[5]}"
    aleo_nodeinfo_number_of_connected_sync_nodes="${nodeinfo_arr[6]}"
    aleo_nodeinfo_version="${nodeinfo_arr[7]}"
    
    #leaderboard
    aleo_leaderboard_position=$(echo $leaderboard | jq ".leaderboard[0].position")
    aleo_leaderboard_cnt_users=$(echo $leaderboard | jq ".count")
    aleo_leaderboard_cnt_blocks_mined=$(echo $leaderboard | jq ".leaderboard[0].blocksMined | length")
    aleo_leaderboard_last_block_mined=$(echo $leaderboard | jq ".leaderboard[0].lastBlockMined")
    aleo_leaderboard_score=$(echo $leaderboard | jq ".leaderboard[0].score")
    aleo_leaderboard_calibration_score=$(echo $leaderboard | jq ".leaderboard[0].calibrationScore")
    aleo_leaderboard_block_heigh=$(echo $leaderboard | jq ".blockHeight")

}

function prometheus_constructor() {

    cat <<EOF >/opt/metrics.d/aleo.metrics
# HELP aleo_nodeinfo_is_miner
# TYPE aleo_nodeinfo_is_miner gauge
aleo_nodeinfo_is_miner $aleo_nodeinfo_is_miner
# HELP aleo_nodeinfo_is_syncing
# TYPE aleo_nodeinfo_is_syncing gauge
aleo_nodeinfo_is_syncing $aleo_nodeinfo_is_syncing

# HELP aleo_nodeinfo_latest_block_height
# TYPE aleo_nodeinfo_latest_block_height gauge
aleo_nodeinfo_latest_block_height $aleo_nodeinfo_latest_block_height
# HELP aleo_nodeinfo_latest_cumulative_weight
# TYPE aleo_nodeinfo_latest_cumulative_weight gauge
aleo_nodeinfo_latest_cumulative_weight $aleo_nodeinfo_latest_cumulative_weight
# HELP aleo_nodeinfo_number_of_candidate_peers
# TYPE aleo_nodeinfo_number_of_candidate_peers gauge
aleo_nodeinfo_number_of_candidate_peers $aleo_nodeinfo_number_of_candidate_peers
# HELP aleo_nodeinfo_number_of_connected_peers
# TYPE aleo_nodeinfo_number_of_connected_peers gauge
aleo_nodeinfo_number_of_connected_peers $aleo_nodeinfo_number_of_connected_peers
# HELP aleo_nodeinfo_number_of_connected_sync_nodes
# TYPE aleo_nodeinfo_number_of_connected_sync_nodes gauge
aleo_nodeinfo_number_of_connected_sync_nodes $aleo_nodeinfo_number_of_connected_sync_nodes
# HELP aleo_nodeinfo_version
# TYPE aleo_nodeinfo_version gauge
aleo_nodeinfo_version $aleo_nodeinfo_version

# HELP aleo_leaderboard_position
# TYPE aleo_leaderboard_position gauge
aleo_leaderboard_position $aleo_leaderboard_position
# HELP aleo_leaderboard_cnt_users
# TYPE aleo_leaderboard_cnt_users gauge
aleo_leaderboard_cnt_users $aleo_leaderboard_cnt_users
# HELP aleo_leaderboard_cnt_blocks_mined
# TYPE aleo_leaderboard_cnt_blocks_mined gauge
aleo_leaderboard_cnt_blocks_mined $aleo_leaderboard_cnt_blocks_mined
# HELP aleo_leaderboard_last_block_mined
# TYPE aleo_leaderboard_last_block_mined gauge
aleo_leaderboard_last_block_mined $aleo_leaderboard_last_block_mined
# HELP aleo_leaderboard_score
# TYPE aleo_leaderboard_score gauge
aleo_leaderboard_score $aleo_leaderboard_score
# HELP aleo_leaderboard_calibration_score
# TYPE aleo_leaderboard_calibration_score gauge
aleo_leaderboard_calibration_score $aleo_leaderboard_calibration_score
# HELP aleo_leaderboard_block_heigh
# TYPE aleo_leaderboard_block_heigh gauge
aleo_leaderboard_block_heigh $aleo_leaderboard_block_heigh
EOF

}

get_Data
metrics_collector

prometheus_constructor

cat $metrics_db

echo >>"$log_file"
echo "Sequence complete without errors." >>"$log_file"
echo >>"$log_file"
